# Generated by Django 4.2.19 on 2025-02-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_username_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
